# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='distribuidos',
  syntax='proto2',
  serialized_options=_b('\n\'com.mateusmelonascimento.socketprotobufB\007Message'),
  serialized_pb=_b('\n\rmessage.proto\x12\x0c\x64istribuidos\"\xb9\x05\n\x07Message\x12(\n\x04\x62ody\x18\x01 \x02(\x0b\x32\x1a.distribuidos.Message.Body\x12\x38\n\x04type\x18\x02 \x02(\x0e\x32!.distribuidos.Message.MessageType:\x07\x44\x45\x46\x41ULT\x12,\n\x06sender\x18\x03 \x01(\x0b\x32\x1c.distribuidos.Message.Sender\x1aI\n\x04\x42ody\x12\x13\n\x0b\x64\x65scription\x18\x01 \x02(\t\x12,\n\x06object\x18\x02 \x01(\x0b\x32\x1c.distribuidos.Message.Object\x1a\"\n\x06Sender\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x1a\x08\n\x06Object\"\xa2\x03\n\x0bMessageType\x12 \n\x1c\x43HANGE_SENSOR_STATUS_REQUEST\x10\x01\x12!\n\x1d\x43HANGE_SENSOR_STATUS_RESPONSE\x10\x02\x12\x1c\n\x18READ_SENSOR_DATA_REQUEST\x10\x03\x12\x1d\n\x19READ_SENSOR_DATA_RESPONSE\x10\x04\x12\x1b\n\x17MULTICAST_SENSOR_FINDER\x10\x05\x12\x1f\n\x1bMULTICAST_SENSOR_FINDER_ACK\x10\x06\x12\x1b\n\x17MULTICAST_SERVER_FINDER\x10\x07\x12\x1f\n\x1bMULTICAST_SERVER_FINDER_ACK\x10\x08\x12\x12\n\x0eUPTIME_REQUEST\x10\t\x12\x13\n\x0fUPTIME_RESPONSE\x10\n\x12\x12\n\x0eREQNUM_REQUEST\x10\x0b\x12\x13\n\x0fREQNUM_RESPONSE\x10\x0c\x12\x1c\n\x18\x43LOSE_CONNECTION_REQUEST\x10\r\x12\x18\n\x14\x43LOSE_CONNECTION_ACK\x10\x0e\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x0f\x42\x32\n\'com.mateusmelonascimento.socketprotobufB\x07Message')
)



_MESSAGE_MESSAGETYPE = _descriptor.EnumDescriptor(
  name='MessageType',
  full_name='distribuidos.Message.MessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CHANGE_SENSOR_STATUS_REQUEST', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHANGE_SENSOR_STATUS_RESPONSE', index=1, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='READ_SENSOR_DATA_REQUEST', index=2, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='READ_SENSOR_DATA_RESPONSE', index=3, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MULTICAST_SENSOR_FINDER', index=4, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MULTICAST_SENSOR_FINDER_ACK', index=5, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MULTICAST_SERVER_FINDER', index=6, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MULTICAST_SERVER_FINDER_ACK', index=7, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UPTIME_REQUEST', index=8, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UPTIME_RESPONSE', index=9, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REQNUM_REQUEST', index=10, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REQNUM_RESPONSE', index=11, number=12,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLOSE_CONNECTION_REQUEST', index=12, number=13,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLOSE_CONNECTION_ACK', index=13, number=14,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEFAULT', index=14, number=15,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=311,
  serialized_end=729,
)
_sym_db.RegisterEnumDescriptor(_MESSAGE_MESSAGETYPE)


_MESSAGE_BODY = _descriptor.Descriptor(
  name='Body',
  full_name='distribuidos.Message.Body',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='description', full_name='distribuidos.Message.Body.description', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='object', full_name='distribuidos.Message.Body.object', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=189,
  serialized_end=262,
)

_MESSAGE_SENDER = _descriptor.Descriptor(
  name='Sender',
  full_name='distribuidos.Message.Sender',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='distribuidos.Message.Sender.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='distribuidos.Message.Sender.port', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=264,
  serialized_end=298,
)

_MESSAGE_OBJECT = _descriptor.Descriptor(
  name='Object',
  full_name='distribuidos.Message.Object',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=300,
  serialized_end=308,
)

_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='distribuidos.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='body', full_name='distribuidos.Message.body', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='distribuidos.Message.type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=15,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sender', full_name='distribuidos.Message.sender', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_MESSAGE_BODY, _MESSAGE_SENDER, _MESSAGE_OBJECT, ],
  enum_types=[
    _MESSAGE_MESSAGETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=729,
)

_MESSAGE_BODY.fields_by_name['object'].message_type = _MESSAGE_OBJECT
_MESSAGE_BODY.containing_type = _MESSAGE
_MESSAGE_SENDER.containing_type = _MESSAGE
_MESSAGE_OBJECT.containing_type = _MESSAGE
_MESSAGE.fields_by_name['body'].message_type = _MESSAGE_BODY
_MESSAGE.fields_by_name['type'].enum_type = _MESSAGE_MESSAGETYPE
_MESSAGE.fields_by_name['sender'].message_type = _MESSAGE_SENDER
_MESSAGE_MESSAGETYPE.containing_type = _MESSAGE
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {

  'Body' : _reflection.GeneratedProtocolMessageType('Body', (_message.Message,), {
    'DESCRIPTOR' : _MESSAGE_BODY,
    '__module__' : 'message_pb2'
    # @@protoc_insertion_point(class_scope:distribuidos.Message.Body)
    })
  ,

  'Sender' : _reflection.GeneratedProtocolMessageType('Sender', (_message.Message,), {
    'DESCRIPTOR' : _MESSAGE_SENDER,
    '__module__' : 'message_pb2'
    # @@protoc_insertion_point(class_scope:distribuidos.Message.Sender)
    })
  ,

  'Object' : _reflection.GeneratedProtocolMessageType('Object', (_message.Message,), {
    'DESCRIPTOR' : _MESSAGE_OBJECT,
    '__module__' : 'message_pb2'
    # @@protoc_insertion_point(class_scope:distribuidos.Message.Object)
    })
  ,
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:distribuidos.Message)
  })
_sym_db.RegisterMessage(Message)
_sym_db.RegisterMessage(Message.Body)
_sym_db.RegisterMessage(Message.Sender)
_sym_db.RegisterMessage(Message.Object)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
